<?php

/*
 * This file is part of the Omed project.
 *
 * (c) Anthonius Munthi <https://itstoni.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

declare(strict_types=1);

namespace spec\Omed\Bundle\Core\Application;

use Omed\Bundle\Core\Application\Kernel;
use Symfony\Component\DependencyInjection\Loader\Configurator\ContainerConfigurator;

class TestKernel extends Kernel
{
    public function getProjectDir()
    {
        return realpath(__DIR__.'/../../../../tests/sandbox/symfony');
    }

    public function configureContainer(ContainerConfigurator $container): void
    {
        parent::configureContainer($container); // TODO: Change the autogenerated stub
    }
}
